import { internalMutation } from "../_generated/server";
import { v } from "convex/values";

export const createDemoData = internalMutation({
  args: {},
  returns: v.object({
    companiesCreated: v.number(),
    message: v.string(),
  }),
  handler: async (ctx) => {
    // Check if demo data already exists
    const existingCompanies = await ctx.db.query("companies").collect();
    if (existingCompanies.length > 0) {
      return {
        companiesCreated: existingCompanies.length,
        message: "Demo data already exists",
      };
    }

    const demoCompanies = [
      // AI Startups
      {
        name: "NeuralFlow AI",
        description: "Advanced neural network optimization for edge computing devices",
        website: "https://neuralflow.ai",
        location: "San Francisco, CA",
        yearFounded: 2021,
        headcount: 45,
        industry: "AI",
        sector: "Software",
        fundingStage: "Series A",
        totalFunding: 12000000,
        revenue: 2500000,
        growthRate: 180,
        employeeGrowthRate: 120,
        keyTechnologies: ["Neural Networks", "Edge Computing", "TensorFlow", "CUDA"],
        competitivePosition: "Emerging",
        acquisitionSuitability: 8,
        investmentPotential: 9,
        patents: 3,
        technicalDifferentiators: ["Proprietary neural compression", "Real-time optimization"],
      },
      {
        name: "DataMind Corp",
        description: "Enterprise AI platform for predictive analytics and automation",
        website: "https://datamind.com",
        location: "Boston, MA",
        yearFounded: 2019,
        headcount: 120,
        industry: "AI",
        sector: "Platform",
        fundingStage: "Series B",
        totalFunding: 35000000,
        revenue: 8500000,
        growthRate: 145,
        employeeGrowthRate: 85,
        keyTechnologies: ["Machine Learning", "AutoML", "Python", "Kubernetes"],
        competitivePosition: "Challenger",
        acquisitionSuitability: 7,
        investmentPotential: 8,
        patents: 8,
        technicalDifferentiators: ["No-code ML platform", "Enterprise integration"],
      },
      // IoT Companies
      {
        name: "ConnectEdge Systems",
        description: "Industrial IoT sensors and edge computing solutions",
        website: "https://connectedge.io",
        location: "Austin, TX",
        yearFounded: 2020,
        headcount: 65,
        industry: "IoT",
        sector: "Hardware",
        fundingStage: "Series A",
        totalFunding: 18000000,
        revenue: 4200000,
        growthRate: 220,
        employeeGrowthRate: 95,
        keyTechnologies: ["LoRaWAN", "Edge Computing", "ARM Cortex", "MQTT"],
        competitivePosition: "Emerging",
        acquisitionSuitability: 9,
        investmentPotential: 8,
        patents: 12,
        technicalDifferentiators: ["Ultra-low power design", "Mesh networking"],
      },
      {
        name: "SmartGrid Dynamics",
        description: "IoT solutions for smart grid and energy management",
        website: "https://smartgriddynamics.com",
        location: "Denver, CO",
        yearFounded: 2018,
        headcount: 85,
        industry: "IoT",
        sector: "Infrastructure",
        fundingStage: "Series B",
        totalFunding: 28000000,
        revenue: 6800000,
        growthRate: 165,
        employeeGrowthRate: 70,
        keyTechnologies: ["Zigbee", "WiFi 6", "Time Series DB", "React"],
        competitivePosition: "Challenger",
        acquisitionSuitability: 6,
        investmentPotential: 7,
        patents: 15,
        technicalDifferentiators: ["Grid-scale optimization", "Predictive maintenance"],
      },
      // Cybersecurity
      {
        name: "SecureVault Technologies",
        description: "Zero-trust security platform for cloud-native applications",
        website: "https://securevault.tech",
        location: "Seattle, WA",
        yearFounded: 2020,
        headcount: 55,
        industry: "Cybersecurity",
        sector: "Software",
        fundingStage: "Seed",
        totalFunding: 8500000,
        revenue: 1800000,
        growthRate: 280,
        employeeGrowthRate: 140,
        keyTechnologies: ["Zero Trust", "Kubernetes", "Go", "gRPC"],
        competitivePosition: "Emerging",
        acquisitionSuitability: 8,
        investmentPotential: 9,
        patents: 2,
        technicalDifferentiators: ["Container-native security", "Policy automation"],
      },
      {
        name: "ThreatShield AI",
        description: "AI-powered threat detection and response for enterprises",
        website: "https://threatshield.ai",
        location: "New York, NY",
        yearFounded: 2019,
        headcount: 95,
        industry: "Cybersecurity",
        sector: "Platform",
        fundingStage: "Series A",
        totalFunding: 22000000,
        revenue: 5200000,
        growthRate: 195,
        employeeGrowthRate: 110,
        keyTechnologies: ["Machine Learning", "SIEM", "Python", "Elasticsearch"],
        competitivePosition: "Challenger",
        acquisitionSuitability: 7,
        investmentPotential: 8,
        patents: 6,
        technicalDifferentiators: ["Behavioral analytics", "Real-time response"],
      },
      // Fintech
      {
        name: "PayFlow Innovations",
        description: "B2B payment infrastructure for emerging markets",
        website: "https://payflow.co",
        location: "Miami, FL",
        yearFounded: 2021,
        headcount: 35,
        industry: "Fintech",
        sector: "Infrastructure",
        fundingStage: "Seed",
        totalFunding: 6000000,
        revenue: 1200000,
        growthRate: 320,
        employeeGrowthRate: 180,
        keyTechnologies: ["Blockchain", "Node.js", "PostgreSQL", "Redis"],
        competitivePosition: "Emerging",
        acquisitionSuitability: 9,
        investmentPotential: 9,
        patents: 1,
        technicalDifferentiators: ["Cross-border optimization", "Regulatory compliance"],
      },
      {
        name: "CreditAI Labs",
        description: "Alternative credit scoring using machine learning",
        website: "https://creditai.com",
        location: "Chicago, IL",
        yearFounded: 2020,
        headcount: 42,
        industry: "Fintech",
        sector: "Software",
        fundingStage: "Series A",
        totalFunding: 15000000,
        revenue: 3100000,
        growthRate: 240,
        employeeGrowthRate: 125,
        keyTechnologies: ["Machine Learning", "Python", "Apache Spark", "Kafka"],
        competitivePosition: "Emerging",
        acquisitionSuitability: 8,
        investmentPotential: 8,
        patents: 4,
        technicalDifferentiators: ["Alternative data sources", "Real-time scoring"],
      },
      // Healthtech
      {
        name: "BioSense Diagnostics",
        description: "Wearable biosensors for continuous health monitoring",
        website: "https://biosense.health",
        location: "Palo Alto, CA",
        yearFounded: 2019,
        headcount: 78,
        industry: "Healthtech",
        sector: "Hardware",
        fundingStage: "Series B",
        totalFunding: 32000000,
        revenue: 7200000,
        growthRate: 175,
        employeeGrowthRate: 90,
        keyTechnologies: ["Biosensors", "Bluetooth LE", "Flutter", "TensorFlow Lite"],
        competitivePosition: "Challenger",
        acquisitionSuitability: 7,
        investmentPotential: 8,
        patents: 18,
        technicalDifferentiators: ["Non-invasive monitoring", "FDA approval"],
      },
      {
        name: "MedFlow AI",
        description: "AI-powered clinical workflow optimization for hospitals",
        website: "https://medflow.ai",
        location: "Philadelphia, PA",
        yearFounded: 2020,
        headcount: 52,
        industry: "Healthtech",
        sector: "Software",
        fundingStage: "Series A",
        totalFunding: 19000000,
        revenue: 4500000,
        growthRate: 210,
        employeeGrowthRate: 105,
        keyTechnologies: ["Natural Language Processing", "FHIR", "React", "MongoDB"],
        competitivePosition: "Emerging",
        acquisitionSuitability: 8,
        investmentPotential: 9,
        patents: 5,
        technicalDifferentiators: ["Clinical NLP", "EHR integration"],
      },
    ];

    let companiesCreated = 0;
    for (const company of demoCompanies) {
      await ctx.db.insert("companies", {
        ...company,
        lastUpdated: Date.now(),
      });
      companiesCreated++;
    }

    return {
      companiesCreated,
      message: `Successfully created ${companiesCreated} demo companies`,
    };
  },
});
